[package]
name = "antarc"
version = "0.1.0"
authors = ["meowjesty <meowjesty_nyan@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = { version = "*", features = ["std", "nightly"] }

[[example]]
name="hello_antarc"
path="examples/hello_antarc/main.rs"
test = true
