[package]
name = "antarc-dummy"
publish = false
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antarc-protocol = { path = "../antarc-protocol" }
log = { version = "*" }
