on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Nightly Rust check + clippy + miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy, miri
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Run cargo miri
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test